version: 2

# Set the version of Python and other tools you might need
build:
  apt_packages:
    - jekyll
  tools:
    python: "3.10"
  # commands:
  #   - bundle install
  #   - bundle exec jekyll build -d _readthedocs/html/

